### ISSUE TITLE
NPC conflict: Quack (Duck) + Fisher Take

### ISSUE THREAD

**Issue by Yukitty** [LuigiBlood/sat_wave#2]
Quack bashes Fisher Take's sprite memory, so don't allow them together.

**Comment by ToontownLittleCat** [comment]
Both Quack and Fisher Take seems okay to me, at least visually.  (This is taken with only the two NPCs are enabled, maybe something else is causing it?)
![image](https://user-images.githubusercontent.com/5963757/35254172-8644a74e-ffbf-11e7-9908-b191ced3df43.png)

**Comment by Yukitty** [comment]
Hmm, you're right, it does work when just the two of them are enabled... 🙁 Time for more testing.

**Comment by Yukitty** [comment]
At this point I am assuming that the 5 NPC limit is just one too high and you can generally only get 4 NPCs total in most cases unless there's some specific combination exception(s) to that. Sorry, nevermind. 😞

**Comment by LuigiBlood** [comment]
The NPC limit is forced by BS-X itself.
