### ISSUE TITLE
Mac Port

### ISSUE THREAD

**Issue by ninonook1** [LuigiBlood/sat_wave#21]
I'm wondering when there will be a mac port for this app. will it be soon or a lot later?

**Comment by LuigiBlood** [comment]
I have no plans because I don't have a Mac and not planning for it any time soon.

**Comment by LuigiBlood** [comment]
If someone wants to make a Mac port, I would love to merge the code and study it.
That said I do not use anything specific so maybe Mono would just work for it just fine?

**Comment by ninonook1** [comment]
well, rip. I hope the project goes well. It looks really promising. I've been using a wine emulator to run it, but I encountered a problem exporting the files. Saving to an XML and editing the file, I have no problems with it, just the exporting; it just gives me an error when attempting it. I don't believe you would have a reason to fix it because it's an emulation problem, not an application problem.

But thanks for letting me know about your plans!

**Comment by LuigiBlood** [comment]
I do use the old .NET so I do expect Mono to work fine, maybe try that on Mac.

**Comment by ninonook1** [comment]
well, I spent 5 hours trying to figure out mono and get it to work, but ultimately i couldn't get it to work. i don't really know what video or article to really help me use mono. but i did think of something that might work, though not related to mono, and have no experience in doing it... which is making it a web application as well... other than that ill keep trying to learn mono

**Comment by LuigiBlood** [comment]
I'll maybe think of a Mac version once I get to know how the real Satellaview works and that we'll have to finally make tools for a real server the way I wanna implement it.

**Comment by ninonook1** [comment]
well take your time, there is no rush for perfection
