### ISSUE TITLE
Event Plaza Collision Bug

### ISSUE THREAD

**Issue by Mekeninzo** [LuigiBlood/sat_wave#26]
As I've been using the Event Plaza Editor to restore some of the recently released Plazas on Satella blog I'm noticing the "Over the player" Collision checkbox does not work for tiles located in the bottom half of the Collision editor for some reason. Not sure if this is an intended feature, but it doesn't seem like it should work like that.

Starting with the top left corner and counting left to right, tiles 1-28 work fine. Tiles 29-47 do not. Tile 48 doesn't even allow a tile to be saved in this spot.

Most of the time I can work around this by moving tile locations. Only problem is the Sim building because it uses so many tiles. (I need an extra 2 tile slots)

I've also noticed times where  "Over the player" is unchecked and moving off the tile puts the player under that tile. Moving the tile to another spots fixes this issue, so it's only a bit annoying.

I'll look through the code when I have time and see if I can figure out why this is happening.

**Comment by LuigiBlood** [comment]
I totally think it's a bug on BS-X because I don't see anything wrong in SatellaWave. I need to look into it more but I don't know what causes the bug.

**Comment by LuigiBlood** [comment]
Found the issue. The priority bit isn't set for the tile map info.

**Comment by LuigiBlood** [comment]
By the way, the last tile not being taken into account is I believe because BS-X is buggy with it.

**Comment by LuigiBlood** [comment]
This should be fixed now.
https://github.com/LuigiBlood/sat_wave/commit/60b27ef1b27a80e03ccf54d4ad5da39ac159e8e0

**Comment by Mekeninzo** [comment]
Awesome! Thanks dawg. I'll test this out when I get home

**Comment by Mekeninzo** [comment]
Test Complete. This works great now! ~Issue Closed~
