### ISSUE TITLE
Suggestion: A 10 File/Item Limit in Folders

### ISSUE THREAD

**Issue by ToontownLittleCat** [LuigiBlood/sat_wave#3]
If you add more then 10 items in a folder in SatellaWave, BS-X will only show the first 10 items defined in the packet and ignores the rest.  This will probably be annoying knowing that some buildings have predefined items being included first alongside with custom items, especially with the Convenience Center having a total of a whopping 8 predefined items.

The program will probably need to have a 10 item limit check, which prevents the user of overfilling the game's own limit, including an unique hard-coded number for each building that has predefined items.  (8 for the Convenience Center, 4 for the sewerage, etc.)

**Comment by LuigiBlood** [comment]
I admit that's a part I haven't tested much.
That's a good suggestion.

**Comment by LuigiBlood** [comment]
I will not forcefully remove items just in case people doesn't want to lose anything. But this should account for most of the potential issues.
